spring.application.name=vetweb

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.forward-headers-strategy=native
logging.level.org.springframework.web=trace
logging.level.org.hibernate=trace
logging.level.com=TRACE
logging.file.name=backend.log
logging.file.path=C:/Users/kevca/dev/java-workspace/vet-system-web